/**
 * Sitemap.xml Generator — Nuxt 4 Nitro Route Handler
 * 输出符合 sitemaps.org 0.9 标准的 sitemap，包含所有语言版本的 hreflang 替代。
 *
 * 覆盖页面：
 *  - Public pages: index, practice, paraphrase, grammar, ranking,
 *                  terms, privacy, login, register
 *  - Auth-protected pages (dashboard/history etc) 用 noindex，不列入 sitemap
 *
 * 每种语言 4 个 locale，每页带 xhtml:link rel="alternate" hreflang。
 */

import { defineEventHandler, setHeader } from 'h3'

type Locale = { code: string; iso: string; dir?: 'ltr' | 'rtl' }

const LOCALES: Locale[] = [
  { code: 'zh-hans', iso: 'zh-Hans-CN' },
  { code: 'zh-hant', iso: 'zh-Hant-TW' },
  { code: 'en',      iso: 'en-US' },
  { code: 'ja',      iso: 'ja-JP' },
]

type PageDef = {
  /** Path 不含 locale 前缀，如 /practice */
  path: string
  /** 每页相对优先级 0.0 ~ 1.0 */
  priority: number
  /** 更新频率 (always/hourly/daily/weekly/monthly/yearly/never) */
  changefreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never'
  /** 是否为首页或重要落地页 */
  landing?: boolean
}

const PAGES: PageDef[] = [
  { path: '/',               priority: 1.0,  changefreq: 'weekly',  landing: true },
  { path: '/practice',       priority: 0.9,  changefreq: 'weekly',  landing: true },
  { path: '/paraphrase',     priority: 0.9,  changefreq: 'weekly',  landing: true },
  { path: '/grammar',        priority: 0.9,  changefreq: 'weekly',  landing: true },
  { path: '/ranking',        priority: 0.7,  changefreq: 'daily'                        },
  { path: '/login',          priority: 0.4,  changefreq: 'monthly'                       },
  { path: '/register',       priority: 0.5,  changefreq: 'monthly'                       },
  { path: '/terms',          priority: 0.3,  changefreq: 'yearly'                        },
  { path: '/privacy',        priority: 0.3,  changefreq: 'yearly'                        },
]

function escapeXml(s: string): string {
  return s
    .replace(/&/g,  '&amp;')
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
    .replace(/'/g,  '&apos;')
}

/**
 * 为当前页面 + 所有语言版本生成 <url> 节点，
 * 每个节点内嵌 <xhtml:link rel="alternate" hreflang="xx-YY" />。
 */
function buildUrlBlock(
  page: PageDef,
  locale: Locale,
  allLocales: Locale[],
  baseUrl: string,
  lastmodIso: string,
): string {
  const fullPath = `/${locale.code}${page.path === '/' ? '' : page.path}`
  const loc = `${baseUrl}${fullPath}`

  const alternates = allLocales
    .map((l) => {
      const p = `/${l.code}${page.path === '/' ? '' : page.path}`
      return `    <xhtml:link rel="alternate" hreflang="${l.iso}" href="${escapeXml(`${baseUrl}${p}`)}" />`
    })
    .join('\n')

  // x-default: 当用户语言不匹配任何 locale 时回退到 zh-hans
  const defaultPath = `/zh-hans${page.path === '/' ? '' : page.path}`
  const defaultLink = `    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(`${baseUrl}${defaultPath}`)}" />`

  return [
    '  <url>',
    `    <loc>${escapeXml(loc)}</loc>`,
    `    <lastmod>${lastmodIso}</lastmod>`,
    `    <changefreq>${page.changefreq}</changefreq>`,
    `    <priority>${page.priority.toFixed(1)}</priority>`,
    alternates,
    defaultLink,
    '  </url>',
  ].join('\n')
}

export default defineEventHandler((event) => {
  // 一律使用配置的正式站点域名（NUXT_PUBLIC_SITE_URL / 默认 sentencegym.waterspo.top）。
  // 不能从请求头推导：云函数 origin 收到的 Host 是内部 pages-scf 域名、协议是 http，
  // 直接推导会生成外部无法访问的 sitemap 链接。
  const config = useRuntimeConfig()
  const baseUrl = String(config.public.siteUrl || 'https://sentencegym.waterspo.top').replace(/\/+$/, '')

  // 使用构建时间或最近修改时间作为 lastmod
  const lastmodIso = new Date().toISOString().split('T')[0] as string

  const urlBlocks: string[] = []
  for (const locale of LOCALES) {
    for (const page of PAGES) {
      urlBlocks.push(buildUrlBlock(page, locale, LOCALES, baseUrl, lastmodIso))
    }
  }

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by Sentence Gymnasium sitemap handler -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml"',
    '        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
    '        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9',
    '            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd',
    '            http://www.w3.org/1999/xhtml',
    '            http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd">',
    urlBlocks.join('\n'),
    '</urlset>',
  ].join('\n')

  setHeader(event, 'Content-Type', 'application/xml; charset=utf-8')
  setHeader(event, 'Cache-Control', 'public, max-age=3600, must-revalidate')
  setHeader(event, 'X-Content-Type-Options', 'nosniff')

  return xml
})
